Filter event logs by realm
google/exposure-notifications-verification-server pull request #1040
Opened 2020-11-10 05:23 UTC by whaught

## Proposed Changes

* Links from the system-admin realm page to event logs for that realm

TODO: show a filter icon to remove the filter and go back to all realms

2020-11-10 14:22 UTC, sethvargo requested changes
I like the idea, but I think I'd rather force people to join the realm and view the realm's event page. I also wonder if we should change the system events page to be _only_ system events.

2020-11-10 16:07 UTC, whaught commented
> I like the idea, but I think I'd rather force people to join the realm and view the realm's event page. I also wonder if we should change the system events page to be _only_ system events.

I think this is pretty cool - we've sort of done this with mobile_apps and users shows both all and admin! Added in a filter for only system events

2020-11-17 19:30 UTC, sethvargo requested changes

2020-11-17 19:30 UTC, sethvargo commented on pkg/controller/admin/events.go
> +	QueryRealmIDSearch = "realmid"
```suggestion
	QueryRealmIDSearch = "realm_id"
```

Maybe?

2020-11-17 19:30 UTC, sethvargo commented on pkg/controller/admin/events.go
> +		if realmID == "0" {
```suggestion
		if realmID == "0" || realmID == "" {
```

2020-11-17 19:30 UTC, sethvargo commented on pkg/database/realm.go
> +	scopes = append(scopes, WithAuditRealmID(fmt.Sprint(r.ID)))
```suggestion
	scopes = append(scopes, WithAuditRealmID(strconv.FormatUint(r.ID, 10)))
```

2020-11-17 19:30 UTC, sethvargo commented on pkg/database/scopes.go
> +func WithAuditRealmID(r string) Scope {
I'm not a huge fan of this accepting a string. I'd rather accept an interface{} or uint.

2020-11-17 20:23 UTC, sethvargo approved these changes
/lgtm

2020-11-17 20:23 UTC, merged