[WIP] E2E coverage for bulk issue
google/exposure-notifications-verification-server pull request #1376
Opened 2020-12-15 22:22 UTC by whaught

Fixes #

## Proposed Changes

*
*
*

**Release Note**

```release-note

```

2020-12-15 23:03 UTC, whaught commented
/retest

2020-12-15 23:33 UTC, sethvargo commented on internal/envstest/server.go
> +		listener.Close()
Check error

2020-12-16 22:31 UTC, mariliamelo requested changes

2020-12-16 22:31 UTC, mariliamelo commented on pkg/clients/apis.go
> +// BatchIssueCode uses the ADMIN API to issue a multiple verification codes.
nit: s/a multiple/multiple

2020-12-16 22:33 UTC, mariliamelo approved these changes

2020-12-16 22:36 UTC, merged