[WIP] Onboarding in ens:// spec
google/exposure-notifications-verification-server pull request #1610
Opened 2021-01-15 19:19 UTC by mikehelmick

## Proposed Changes

* define ens://onboard in the ens:// spec
* no implementation yet.
* 
**Release Note**

```release-note
NONE
```

2021-01-15 19:25 UTC, sethvargo requested changes

2021-01-15 19:25 UTC, sethvargo commented on docs/ens-spec.md
>  -   `v` : verify, currently this is the only available action.
I think this comment is wrong now?

2021-01-15 19:25 UTC, sethvargo commented on docs/ens-spec.md
> +ens://onboard?r=WA-WA
US-WA?

2021-01-15 19:25 UTC, sethvargo commented on docs/ens-spec.md
> +ens://onboard?r=WA-WA
Add a note on case sensitivity?

2021-01-15 19:27 UTC, mikehelmick commented on docs/ens-spec.md
> +ens://onboard?r=WA-WA
added note above on region param

2021-01-15 19:55 UTC, sethvargo approved these changes
/lgtm

2021-01-19 19:38 UTC, sethvargo commented
/lgtm

2021-01-19 19:42 UTC, merged