add translations cache clear
google/exposure-notifications-verification-server pull request #2110
Opened 2021-05-28 21:58 UTC by mikehelmick

## Proposed Changes

* Add clear cache option for translations

**Release Note**

```release-note
none
```

2021-05-29 15:33 UTC, sethvargo requested changes

2021-05-29 15:33 UTC, sethvargo commented on pkg/controller/admin/caches.go
> +	"translations:":       {"Translations", "Realm specific tranlations for the user report webview"},
Nit: these are supposed to be alphabetically sorted

2021-05-30 21:35 UTC, mikehelmick commented
fixed ordering

2021-05-31 00:31 UTC, sethvargo approved these changes

2021-05-31 00:31 UTC, merged