Allow app to disallow particular hostnames
google/exposure-notifications-verification-server pull request #894
Opened 2020-10-26 17:42 UTC by whaught

## Proposed Changes

* Allow server to block particular hostnames
    * Can be used to stop run.app from serving in favor of a custom domain

**Release Note**

```release-note
Allow blocking configured hostnames from serving eg. 'run.app'
```

2020-10-26 18:01 UTC, jeremyfaller requested changes

2020-10-26 18:01 UTC, jeremyfaller commented on pkg/controller/middleware/blockedhosts.go
> +				if strings.HasSuffix(r.Host, host) {
IIRC, `r.Host` can contain the port number. So, `foo.com:80` won't trigger if foo.com is listed. I'd strip the port here.

2020-10-26 18:02 UTC, jeremyfaller commented on pkg/controller/middleware/blockedhosts.go
> +				if strings.HasSuffix(r.Host, host) {
This has another problem in that if the host is myfoo.com, and foo.com is blocked, I will get unintentionally blocked.

2020-10-26 18:06 UTC, icco commented
/cc @yuriatgoogle

2020-10-26 18:10 UTC, icco commented
See https://github.com/google/exposure-notifications-verification-server/issues/871

2020-10-26 18:20 UTC, whaught commented
/hold

All good points about breaking down hostname. This was a quick solution, but looks like folks are leaning towards doing this at the load-balancer level rather than application-level

2020-10-26 21:08 UTC, yuriatgoogle reviewed
The current plan is to use the --ingress flag:
https://cloud.google.com/sdk/gcloud/reference/alpha/run/deploy#--ingress
once it's in GA.  Working to determine timeline for that.

2020-11-06 20:35 UTC, sethvargo commented
@whaught are we good to close this out since the `--ingress` flag seems to be coming soon?

2020-11-06 20:39 UTC, whaught commented
> @whaught are we good to close this out since the `--ingress` flag seems to be coming soon?

Yea this would be an interim solution if we can't figure out --ingress or load balancer. I assume that is coming shortly?

/close

2020-11-06 20:39 UTC, closed without merging